use_frameworks!

platform :ios, '9.0'

target 'HTAppPublic_Example' do
  pod 'HTAppPublic', :path => '../'
#  pod 'HTAppPublic',:git =>"https://github.com/CrazyWX/HTAppPublic.git"

pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
  target 'HTAppPublic_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
